#!/usr/bin/env bash
#Bash script that display the PID along side with the process name, of processes whose name contains the word bash

pids=$(pgrep -f bash)
for pid in $pids;
do
	process_name=$(ps -p $pid -o comm=)
	echo "$pid $process_name"
done
