#!/usr/bin/env bash
#Bash script that displays:

#To infinity and beyond indefinitely
#With a sleep 2 in between each iteration
#I am invincible!!! when receiving a SIGTERM signal

handle_sigterm()
{
	echo "I am invisible!!!"
}

trap handle_sigterm SIGTERM

display_message()
{
	while :
	do
		echo "To infinity and beyond"
		sleep 2
	done
}
#echo "I am invisible!!!"
display_message
echo "I am invisible!!!"
