#!/usr/bin/env bash
#Script that print Best school ten times but on 9th time print "hi" using while loop

counter=0

while [ $counter -lt 10 ];
do
	if [ $counter -eq 8 ];
		then
			echo "Best School"
			echo "Hi"
	else
		echo "Best School"
	fi

	((counter++))
done
