#!/usr/bin/env bash
# A script that that display number from  1 to 20 and display after 4th, 9th, 17th 
#bad luck from China, bad luck from Japan, bad luck from Italy

count=1
while [ $count -le 20 ];
do
	case $count in
		4)
			echo "$count"
			echo "bad luck from China"
			;;
		9)
			echo "$count"
			echo "bad luck from Japan"
			;;
		17)
			echo "$count"
			echo "bad luck from Italy"
			;;
		*)
			echo "$count"
			;;
	esac
	((count++))
done
