#!/usr/bin/env bash
#Script that display content of current directory in list format
#Where only the part of the name after the first dash is displayed (refer to the example)
for file in *; do

	if [[ ! -d $file && ! $file == .* ]];
	then
		name=$(echo "$file" | sed 's/^[^-]*-//')
		echo "$name"
	fi
done
